name: modern_form_stepper
description: A flutter stepper widget with customizations
version: 1.1.1
homepage: https://github.com/apps-auth/modern_form_stepper

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


#flutter: